### ISSUE TITLE
Support for nucmer4?

### ISSUE THREAD

**Issue by flopezo** [nextgenusfs/funannotate#123]
Hello,

I'm using `funannotate clean` to remove redundant contigs from haploid insect genomes, but this process is quite slow. I was wondering if it's possible to use `nucmer4` (https://mummer4.github.io/), which now runs multi-threaded. I'm trying other alternatives as well, such as `psi-cd-hit`, but I'm still interested in following a complete `funannotate` walkthrough.

Thank you!

**Comment by nextgenusfs** [comment]
Yes I know it is kind of slow, especially with a lot of contigs. The approach it is using is a "leave 1 out" method.  I found that I wasn't able to properly remove repetitive contigs by doing an "all vs all".  I have also tried to use minimap2 to do the calculations, but wasn't able to get identical results. The minimap2 option is actually still available in the script, it just isn't documented. You can try minimap2 method by passing `--method minimap2` to the `funannotate clean` script.

It should be possible to use mummer4, have the commands changed? i.e. is it called `nucmer4` instead of `nucmer`?  The fastest way to check out be to unlink mummer3 and then softlink the mummer4 commands. It uses the `nucmer` and `show-coords` scripts from mummer3.  Let me know if you give this a try and if it is faster or not.

**Comment by nextgenusfs** [comment]
And to add, you of course don't need to use `funannotate clean` - I wrote it to clean up an assembly that had a lot of repetitive sequences but have found that it works well to drop many "unplaced" repeats from the assembly.  Either way, they likely won't have a big impact on genome annotation.

**Comment by flopezo** [comment]
Thank you for the detailed reply. I noticed the `minimap2` option in the script. I have used `minimap2` for interspecific full-genome alignment before, but sometimes I get very different top hits in comparison to, say, `dc-megablast`.

Yes, it's still called `nucmer` and I think the commands haven't changed. I'm using the most recent version ([v.4.0.0.beta2](https://github.com/mummer4/mummer/releases/tag/v4.0.0beta2)), which compiled without errors. I started running `funannotate clean` with this new `nucmer` and it seems to be working fine.
