### ISSUE TITLE
brew install funannotate fails at "repeatmodeler"

### ISSUE THREAD

**Issue by cktheory** [nextgenusfs/funannotate#15]
My "brew install funannotate" install kept getting held up and the perl ./configure <config.txt.

I decided to install the program myself to the usr/local directory following the config.txt of the failed installation and I noticed in the config.txt file that all of the paths listed were written as /home/linuxbrew/.linuxbrew/... rather than $HOME/.linuxbrew/... This is why the perl script was stuck in an endless loop, the target directories didn't exist. I don't know if you control that file but it is an error in the config.txt of repeatmodeler

**Comment by nextgenusfs** [comment]
I did not write the formula for `repeatmodeler`, you can find it  [here](https://github.com/Homebrew/homebrew-science/blob/master/repeatmodeler.rb).  But if it is installed via LinuxBrew, then the default install location for LinuxBrew is used (which is $HOME/.linuxbrew).  Did you install LinuxBrew to another location or used the default?  I have been able to install `repeatmodeler` via LinuxBrew on both Ubuntu and centOS 7, so not entirely sure what the problem is/was.  You can always install the tools manually, it is just a large amount of work - hence the home-brew formula.  `funannotate` will check for required software prior to running and tell you what is not installed.  The `setup.sh` script also does this.

Were you able to get it working after installing `repeatmodeler` manually?

**Comment by cktheory** [comment]
I used the default install instructions for homebrew following the ubuntu tutorial. I had to brew update before I could install anything though. And it is odd that the config.txt file was created with /home/linuxbrew/.linuxbrew/ since my account is named funannotate so it should have been home/funannotate/... To pass the ./setup script I added the directory to my path in .bash_aliases

**Comment by nextgenusfs** [comment]
I will add the `brew update` command to the tutorial.  If you want to file an issue with LinuxBrew over the `repeatmodeler` install, you can do that [here](https://github.com/Linuxbrew/linuxbrew).
