### ISSUE TITLE
diamond shows 0 valid proteins

### ISSUE THREAD

**Issue by aprezvykh** [nextgenusfs/funannotate#154]
Hello!
I tried to use "funannotate annotate" with the following command (i used the last version of funannotate):
`funannotate annotate -i tg1 -o tg1_annotation --busco_db diptera --eggnog tg1/result_tg1.emapper.annotations --cpus 56 `

`funannotate predict` pipeline output was good, with no errors, also it can be said about emapper
but i got this: 

`[Mar 14 02:53 PM]: 0 valid gene/product annotations from 190 total`

full annotation log wil be in this message
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/1810917/funannotate-annotate.log)

It will be great if you will help me with it!
Thank you,
Alexander

**Comment by nextgenusfs** [comment]
It may or may not be an actual error. It found 190 hits that passed the diamond threshold in the UniProtKb database, but 0 of those had proper gene names and product descriptions that it could parse.  It could be possible that your version of diamond is too old and the XML output format isn't being read by funannotate correctly, but also possible that because of the few proteins in your search that there weren't any that met all the criteria.  If you update diamond, you will need to re-build the diamond search databases as diamond databases created with versions less than 0.9.0 are not compatible with newer versions. So basically you will just need to re-run `funannotate setup` and use the `--force` option.  Also if you upgrade diamond, be careful as there are a few versions that have bugs in the XML output format https://github.com/nextgenusfs/funannotate/issues/135.

**Comment by aprezvykh** [comment]
Updating of diamond & database has solved that problem!
