### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by jmonroynieto** [nextgenusfs/funannotate#167]
I tried following the docker install instructions:
http://funannotate.readthedocs.io/en/latest/docker.html#docker

but the container exits with the following error:
```
Starting MySQL...
* The server quit without updating PID file (/home/linuxbrew/.linuxbrew/var/mysql/a8797e0b868c.pid).
```
How can I solve the docker error?

**Comment by nextgenusfs** [comment]
What OS are you on?  I've only tested it with Mac, but sounds like perhaps you are on Linux?  As of the new version, you can probably comment out the mysql section of the `Dockerfile` if that is giving you errors as newest version can use SQLite instead of mysql (but I left the docker container as it was).
