### ISSUE TITLE
About the quality of structure annotate, new PacBio ISOSeq data counting results.

### ISSUE THREAD

**Issue by iwangtoknow** [nextgenusfs/funannotate#199]
**Describe the bug**
From 30/05/18 to 06/06/18 I walked through the funannotate pipeline from clean to annotate, at that time I have a >90% completeness assembly file, Illumina Nova Seq RNA sequencing data (total clean > 20 GB), a little high quality ISOSeq data (<400 reads, due to add sample problem).
The Illumina reads mapped my assembly very well, >60 million reads, Uniquely mapped reads 95.61%.
Now I have a little bit more ISOSeq data, before I re-run the whole pipeline, I mapped the new data to the annotate file to count the coverage of my new data.

**What command did you issue?**
`minimap2 -ax splice -uf -C5 MyAssembly.fa ./long_reads/all.polished.fq > all.polished.sam`
` htseq-count -f sam -t exon all.polished.sam Aspergillus_nidulans_aspbj.edited.gff3 > count.fun.txt`

**Logfiles**
No Logfiles. 

**OS/Install Information**
 -  output of `funannotate check --show-versions`
I used funannotate 1.3.4, I just updated my funannotate docker and could not provided the old --show-versions
ps. I really love docker.

---

@nextgenusfs 

Term | Count
------------ | -------------
total alignments in `all.polished.sam` | 3309
ambiguous alignment to feature  | 2709
reads with feature | 372
reads with no feature | 124
too low Qual | 100
not aligned | 0
alignment not unique | 0

[count.fun.txt](https://github.com/nextgenusfs/funannotate/files/2205683/count.fun.txt)

Jon do you have a similar experience?

WANG

**Comment by nextgenusfs** [comment]
In the latest few versions, I used some Nanopore mRNA direct yeast data and integrated the long reads into `funannotate train` and `funannotate update`. The way I'm running `minimap2` for iso-seq is pretty much the same as you are doing:
```
def iso_seq_minimap2(transcripts, genome, cpus, intron, output):
    '''
    function to align PB iso-seq data
    '''
    bamthreads = int(round(int(cpus) / 2))
    if bamthreads > 4:
        bamthreads = 4
    minimap2_cmd = ['minimap2', '-ax', 'splice', '-t', str(cpus), '--cs', '-uf', '-C5', '-G', str(intron), genome, transcripts]
    cmd = [os.path.join(parentdir, 'util', 'sam2bam.sh'), " ".join(minimap2_cmd), str(bamthreads), output]
    runSubprocess(cmd, '.', log)
```
So how many reads to you have in your Iso-seq data?

You can now load all of the data into `funannotate train` and it should be integrated. It maps the long-reads using `minimap2` and then will run Trinity on the short reads (using the --long_reads option in Trinity). Then the long-reads are mapped against the trinity assembled transcripts and unique long-reads are retained along with trinity transcripts to feed into PASA. This way we use the higher quality trinity sequences coupled with anything else in the long-reads that isn't represented in the short-reads. The scripts then go through the same PASA method, then choose best transcript at each locus using Kallisto and the short read data. 
```
Usage:       funannotate train <arguments>
version:     1.4.2-f5f42de

Description: Script is a wrapper for Illumina RNA-seq data through genome-guided Trinity 
             followed by PASA. Long-read (nanopore/pacbio) RNA-seq is also supported.
             Dependencies are hisat2, Trinity, samtools, fasta, minimap2, blat, PASA.
    
Required:  -i, --input              Genome multi-fasta file.
           -o, --out                Output folder name.
           -l, --left               Left/Forward FASTQ Illumina reads (R1)
           -r, --right              Right/Reverse FASTQ Illumina reads (R2)
           -s, --single             Single ended FASTQ reads

Optional:  --stranded               If RNA-seq library stranded. [RF,FR,F,R,no]
           --left_norm              Normalized left FASTQ reads (R1)
           --right_norm             Normalized right FASTQ reads (R2)
           --single_norm            Normalized single-ended FASTQ reads
           --pacbio_isoseq          PacBio long-reads
           --nanopore_cdna          Nanopore cDNA long-reads
           --nanopore_mrna          Nanopore mRNA direct long-reads
           --trinity                Pre-computed Trinity transcripts (FASTA)
           --jaccard_clip           Turn on jaccard clip for dense genomes [Recommended for fungi]
           --no_normalize_reads     Skip read Normalization
           --no_trimmomatic         Skip Quality Trimming of reads
           --no_antisense_filter    Skip anti-sense filtering.
           --memory                 RAM to use for Jellyfish. Default: 50G
           -c, --coverage           Depth to normalize reads. Default: 50
           --pasa_db                Database to use. Default: sqlite [mysql,sqlite]
           --pasa_alignment_overlap PASA --stringent_alignment_overlap. Default: 30.0
           --max_intronlen          Maximum intron length. Default: 3000
           --species                Species name, use quotes for binomial, e.g. "Aspergillus fumigatus"
           --strain                 Strain name
           --isolate                Isolate name
           --cpus                   Number of CPUs to use. Default: 2

ENV Vars:  If not passed, will try to load from your $PATH. 
           --PASAHOME
           --TRINITYHOME
```

**Comment by iwangtoknow** [comment]
Thx Jon,
According to result I got from HTseq,  does that mean only with short reads transcript evidence, structure annotation still far from the TRUE?

You can see I have >3K polished reads in Iso-seq data.

WANG

**Comment by nextgenusfs** [comment]
I'm not familiar with HTseq, so I'm not exactly sure what you are measuring with that above command. I've also not done PB-isoseq so I don't know exactly what the error rates are or what to expect for full length.  My understanding is that the iso-seq reads are "error-corrected" via PB and should represent full-length sequences?  

What I'm trying to to with the current method in `funannotate` is leverage as much information as you can give it. The Trinity assemblies are more accurate because they are from small reads, i.e. they map to the genome at close to 100% identify, whereas (at least with nanopore data) the errors are still quite high so that mapping identity is lower - but generally `minimap2` is still able to map these data.  I'm assuming that HTseq is built for short reads and likely illumina data, so it maybe parsing your sam file differently than you might think in terms of mapping quality, etc.  Brian Haas has experimented with using the long-reads in Trinity and found that with the current algorithms the data has too many errors to work as it was intended, thus there is a long-reads option in trinity where the long reads are used to scaffold the short reads (at least that is what docs suggest). 

The current funannotate implementation will use all the data you give it to generate a unique set of transcripts, those then get passed to PASA, and then during the predict step those same transcript alignments also get passed to Evidence Modeler (this happens automatically by the scripts if you run `funannotate train` first). Finally the data is used again during `funannotate update` when the scripts use the annotation in comparison to the PASA database (which will have all alignments from short and long reads), and PASA will try to extend gene models UTRs, remove unsupported models, and find new models if there is support in the alignment data.

**Comment by iwangtoknow** [comment]
Thx Jon! 
HTseq is a python package can count how many reads cover a feature in structure annotation.
I'll re-run funannotate use version 1.4.2.

**WANG**

**Comment by iwangtoknow** [comment]
Sorry Jon,
I made a mistake run HTseq with `-t exon`, should be `-t gene`
And re-new the form.
Term | Count
------------ | -------------
total alignments in `all.polished.sam` | 3309
ambiguous alignment to feature  | 229
reads with feature | 3282
reads with no feature | 124
too low Qual | 100
not aligned | 0
alignment not unique | 0
