### ISSUE TITLE
Support alternate predictors? CodingQuarry

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate#200]
Had a request to support CodingQuarry: https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1344-4.  I've gotten it installed - which was fairly straightforward, although required a version of GCC > 4.8. I've also run into a few segmentation faults for unknown reasons.  However, I have also managed to run it with a small number of tests thus far.  Since it requires RNA-seq, or rather transcripts aligned to the genome in GFF format, and the documentation isn't obvious on what it is doing or whether it works for higher eukaryotes or only fungi?, I'm hesitant to include it into funannotate. I also would like to limit dependencies - as it is hard enough to install as it is.  Of course if turns out to be useful and users would like it included, would be relatively straightforward to have funannotate run this if RNA-seq BAM file is passed to `funannotate predict`.

I did however, run it and the results can be passed to funannotate like the following.

1) I aligned PE stranded RNA-seq data using `hisat2` and then converted and sorted the BAM file using samtools.
 ```
hisat2 -x genome -p 8  reads_R1.fq reads_R2.fq | samtools view -bS - | samtools sort -o sorted.bam 
```
2) then ran [StringTie](https://ccb.jhu.edu/software/stringtie/), which will output a GTF file.
```
stringtie -o strin_out.gtf -p 8 sorted.bam
```
3) convert GTF to GFF3 using funannotate script
```
funannotate util stringtie2gff3 -i string_out.gtf > string_out.gff3
```
4) then run CodingQuarry using default settings
```
CodingQuarry -t string_out.gff3 -f genome.fasta -p 8
```
5) Convert malformed GFF3 output to proper GFF3 format. 
```
funannotate util quarry2gff3 -i out/PredictedPass.gff3 > coding-quarry.gff3
```
6) finally can pass this to `funannotate predict` like following, note I gave it a weight of 5 for EVM with the `:5` option:
```
funannotate predict -i genome.fasta -o test \
        --other_gff coding-quarry.gff3:5 \
        --cpus 12 -s "Awesome genome"
```

**Comment by BenjaminSchwessinger** [comment]
Thanks that is awesome.

**Comment by nextgenusfs** [comment]
Sure no problem. You can run their effector predictor as well (need `signalp` installed) - which outputs two different GFF3 files.  I would convert those separately and you can experiment with weights that you give them in `funannotate predict`. Also, since effectors are often in repeat dense regions, you may need to modify how funannotate filters out repetitive gene models, more here: http://funannotate.readthedocs.io/en/latest/predict.html#how-are-repeats-used-dealt-with. But specifically maybe want to turn off overlap filtering if the effectors are getting dropped from the annotation.

**Comment by nextgenusfs** [comment]
And I should add to the above, that if you have already run `funannotate train` using RNA-seq data, then you can re-ruse the BAM file from hisat2 -- the file will be located at `output_dir/training/hisat2.coordSorted.bam`.  So you can pass this BAM file to `stringtie` or could also use [scallop](https://github.com/Kingsford-Group/scallop).

**Comment by nextgenusfs** [comment]
Great, when I get a few spare moments I'm going to include the stringtie/codingquarry into `funannotate predict` if a BAM file is passed.  I won't make it a hard dependency right away, so it will just get skipped if stringtie or CodingQuarry are not installed.  I need to see some results on larger genomes before making it a hard dependency.

**Comment by cejackson** [comment]
Was there ever any follow-up on CodingQuarry with larger genomes, etc?

I am running funannotate on a 200 Mb crustacean genome, and installed CodingQuarry with funannotate, before realizing it may be more focused towards fungi and not animal genomes.

I noticed CodingQuarry contributing a very high number of gene models to EVM, almost double the number than other predictors - which has me worried about CodingQuarry introducing false positive gene models.

Summary of gene models: {'genemark': 29196, 'hiq': 10013, 'pasa': 21185, 'CodingQuarry': 56426, 'augustus': 16430, 'total': 133250}

Also, I noticed than even though it was mentioned here that CodingQuarry wasn't fully examined, by default it is given a weight of 10 in EVM, comparable to PASA (I assume because both use RNA-seq data).
EVM Weights: {'genemark': '1', 'hiq': '5', 'pasa': '10', 'CodingQuarry': '10', 'augustus': '1'}

And this has me even more worried since those 56,000 CodingQuarry models are given such high priority.

I am going to remove CodingQuarry from PATH, and rerun funannotate predict without CodingQuarry to see how this affects the results, as the numbers of CodingQuarry do seem a bit weird for an animal genome.

**Comment by nextgenusfs** [comment]
Yes that sounds like the RNA-seq assembly/training of CodingQuarry is resulting in fragmented gene predictions.  You could alternatively keep those predictions and pass them to `--other_gff codingquary.gff3:1` which will only give it a weight of `1`. Likely it would be useful to be able to control the EVM weights at runtime for all of the evidence.  You could alternatively modify your local copy to change the weight for those models here: https://github.com/nextgenusfs/funannotate/blob/8f86f8ccb603e717bd32a8a24d090d44e6d57948/bin/funannotate-predict.py#L1170

**Comment by cejackson** [comment]
I decided to just leave out CodingQuarry for this species, as it was adding ~11,000 extra gene models in EVM output (probably would be less if used weight 1 of course), which is way more extra than expected for this species.

I will leave CodingQuarry to the fungi genomes as it was designed for that. I don't know what it's doing on this animal genome differently.

I am getting good results without it.
Just wanted to provide input for other users, that if using funannotate for non-fungi genomes, CodingQuarry may not be a good option to include.
Thanks
