### ISSUE TITLE
Why does funannotate not parse GO terms, etc from EggNOG output?

### ISSUE THREAD

**Issue by jpiechura** [nextgenusfs/funannotate#204]
I'm just curious if there is a practical reason why funannotate only takes EggNOG and COG annotations from the output of emapper. The output from emapper also provides lists of GO terms, KEGG_KOs for each gene, but funannotate does not parse these annotations and thus they are lost by the pipeline as far as I can tell. It would be great to know if there is a practical reason for ignoring the GO terms, etc produced by emapper, or if there is probably usefulness in this data and funannotate just passes over it. Any explanation would be appreciated!

**Comment by nextgenusfs** [comment]
It could certainly be included. I have some reservations on the accuracy and thresholds of the eggnogmapper search. I haven’t included them due to the differences in the way that the searches are done. With interproscan the primary domain searches are done (i.e. pfam, panther, etc) and based on those data are annotated with a interproscan domain/ID. EggnogMapper is really a database of protein families, where the search is done via diamond search, so then all the GO terms etc are simply inherited due to somewhat loose homology to a protein family. 

But to be honest I haven’t spent a lot of time looking/comparing the GO terms derived from each tool. I recall thinking that there seemed like far too many GO terms in the eggnog hits. So I was also concerned about comparing the go terms derived from the two different tools.  If you can point me to a reference or some analysis showing they are indeed comparable and compatible with  interproscan derived GO terms that would be great. 

In general I’m not a huge fan of inherited annotations, I was reluctant to add the gene names and product definitions because of this as well. I know it helps but I worry about annotations being assigned based solely on primary sequence similarity or rather lack there of, e.g. using a single identify threshold across multiple protein families is probably problematic. If we aren’t conservative about assigning annotations then missannotations are much more likely to “spread” unchecked in the future.
