### ISSUE TITLE
Task Runtime Question

### ISSUE THREAD

**Issue by DrPintoThe2nd** [nextgenusfs/funannotate#226]
Hi Jon!

Thanks so much for your work on this!!

Not an issue, but I was just wondering what you expect the runtime of certain tasks to be (in general)?
e.g. sort is super fast, repeatmasking is 1-2 days..., clean has been running for 5 days with no updates?..
I couldn't find anything in my brief search.. :/

Thanks again!
Best,
bjp

**Comment by nextgenusfs** [comment]
Hi @DrPintoThe2nd, this depends of course on the genome size and assembly completeness. 5 days seems like a very long time, but depending on the cpus and/or the number of contigs/lengths I guess it is possible. The clean step is slow because it uses a leave-one-out strategy starting with the shortest contig, so if you have highly fragmented assembly it may take some time. Is the script telling you that any contigs are repeats and dropping them?  It is of course an optional step.

**Comment by DrPintoThe2nd** [comment]
Hi Jon!

Sometimes it would list scaffolds it had discarded, sometimes not... I went ahead and cutoff at >5000bp scaffolds using sort and moved forward.

Thanks so much for your work on this! The docker is working great for me!!!
Best,
bjp
