### ISSUE TITLE
RefSeq option or am I missing something?

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#295]
Quick question.

When my `funannotate annotate ` run is finished I noticed that most of the proteins are classified as "hypothetical proteins" even though some have notes of pfams, GOs, merops, eggnogs, etc. I created a custom script that uses the *.proteins.fasta and the *.annotations.txt to blast my proteins against a reference genome (with >=80% identify and  >=75% alignment length) that has more of it's proteins classified as a particular product and create a custom_annotation.txt file to re-run `funannotate annotate ` and pass it through the -a flag. Doing so allowed me to give product names to over 3,000 of my proteins that were previously classified as "hypothetical". 

My question is, is this normal? Or is there a RefSeq option that I am missing somewhere in the pipeline to better classify proteins?

**Comment by nextgenusfs** [comment]
This is something pretty much everybody asks.  You have to determine what is the "best" thing to do and what are you going to do with your data, funannotate by design is conservative in this respect.  This is for two reasons, 1) NCBI requires a gene name if you have a product definition line so this is tricky to parse because of all the noise in reference databases and 2) I don't think its appropriate to assign gene names and deflines from non-curated/non-experimental data.  

This is because the problem will only get worse, so you have 80% identity to a name in another genome, which presumably was assigned based on some criteria in reference to something else (hopefully a curated dataset such as UniProt).  So if we continue to use some arbitrary threshold to assign gene names, they start to not mean anything after awhile and the "reference" databases become polluted with inappropriate gene names, so you might have assigned a name to a protein in UniProt that you are now several steps removed from and it actually isn't above a reasonable threshold to call that protein name XY or Z.  

So funannotate uses the UniProt/SwissProt curated database and will pull gene names/deflines where it can.  It also uses EggNog where it can and comes up with a consensus gene name.  We've then built a `gene2products` database to try to clean up the deflines and assign something that will pass NCBI rules.  Yes, you are only going to assign gene names/product deflines to about 2000 proteins from a typical fungal genome.  But since we really don't know what most fungal proteins do, this is not "bad", in fact I would argue this is the "best" result.

**Comment by PlantDr430** [comment]
Ah, that makes sense. I guess I am just surprised as how little of the
genes were provided names and products, but I do know that we really don't
know what a lot of these fungal proteins do. I am looking to do some in
depth genomic analysis which could benefit from having an somewhat better
idea of what the proteins "might" be doing instead of just comparing large
amounts of hypothetical proteins. I'll contact NCBI and ask for some advice
as well, but in the meantime I might just be tightening my criteria to >
90% or even higher and placing these annotations as additional 'notes'
instead of 'product' definition lines.
