### ISSUE TITLE
Run funannotate without full RepeatMasker library

### ISSUE THREAD

**Issue by ctxchris** [nextgenusfs/funannotate#31]
Hi Paul,

I don't have access to the full RepeatMasker library. Running funannotate with the minimal library results in an error (Missing full RepeatMasker repeat library). Can I run funannotate anyway with the minimal RepeatMasker library, by skipping the RepeatMasker step or by providing a custom repeat library to RepeatMasker?

Thanks
Chris

**Comment by nextgenusfs** [comment]
Hi Chris,
Funannotate is first creating a custom repeat library using RepeatModeler, it then feeds that data into RepeatMasker to generated a repeat library in GFF format.  It's my understanding that RepeatMasker won't use a custom library without the repeatmasker libraries, I'm not exactly sure why.  But their [installation instructions](http://www.repeatmasker.org/RMDownload.html)  require you to install the libraries.

Due to the linear nature of funannotate, currently there is no way to skip this step.  It is feasible to code it that way, but having the masked genome improves the gene prediction steps.

Why don't you have access? 

It is fairly easy to download/configure - you just need to register for a free account at [RepBase](http://www.girinst.org/repbase/), then do the following:
```
#download RepeatMasker libraries and install
wget --user name --password pass http://www.girinst.org/server/RepBase/protected/repeatmaskerlibraries/repeatmaskerlibraries-20160829.tar.gz
tar zxvf repeatmaskerlibraries-20160829.tar.gz -C /usr/local/opt/repeatmasker/libexec

#now setup RepeatMasker
cd /usr/local/Cellar/repeatmasker/4.0.5/libexec
./configure
```
-Jon

**Comment by ctxchris** [comment]
Hi Jon,

thanks for answering so quickly and sorry for calling you Paul, don't know what happened there :)
RepBase unfortunately is only free for academic use and I'm no more academic.
I've used RepeatMasker in the past mostly with the -lib option that allows for the use of a custom repeat library. If I remember correctly the program won't use the standard library.

Chris

**Comment by nextgenusfs** [comment]
Hi Chris,
Not sure if you found a work-around or not?  I can add some options to pass perhaps something like `--masked_genome` and `--repeatmasker_gff3` options where you could do these steps outside of funannotate (both options would likely be required).  The reason that the repeat masking is important is that I use the GFF3 file to filter repetitive gene models, additionally the ab initio predictors use the soft masked genome to avoid problems with calling gene models near/on repetitive elements.

**Comment by ctxchris** [comment]
Hi Jon,

I ended up with executing the individual steps of the pipeline manually.
The two options you propose sound great. 

Chris

**Comment by nextgenusfs** [comment]
Hi Chris.  For future reference, v0.5.5 now supports bypassing repeatmodeler and repeat masker, the options above can be passed to skip those steps.

**Comment by nextgenusfs** [comment]
This has now been updated further -- I've decoupled the repeat-masking step from `funannotate predict`.  Users can now run the previous RepeatModeler/Masker method using the `funannotate mask` command -- `funannotate predict` is expecting a soft masked genome and will warn you if it is not soft masked. This should be more flexible for users that can't use repeatmodeler/masker due to the RepBase license.  I've tried to find an alternative, one software I've recently looked into is `Red` - if anybody is interested I wrote a wrapper around it for ease of use and generating a bed file from the repeats it identifies, located at https://github.com/nextgenusfs/redmask. `Red` is fast and has no dependencies, but I won't be incorporating it into funannotate as in my preliminary tests it seems to overmask repeats for some fungal genomes.  Hopefully this makes funannotate more flexible/useful.
