### ISSUE TITLE
what is Custom annotations

### ISSUE THREAD

**Issue by shenweima** [nextgenusfs/funannotate#329]
In the `*.annotations.txt` file,  all protein is "hypothetical protein".

![test](https://user-images.githubusercontent.com/8536868/65927652-252edc00-e42d-11e9-987a-d00779ff7e7d.jpg)

This is my commond
`funannotate annotate --gff IWGSC_v1.1_HC_20170706.gff3 --fasta /data2/Fshare/FastaAndIndex/IWGSC_v1.0_bwa/161010_Chinese_Spring_v1.0_pseudomolecules.fasta -s "Triticum aestivum" --sbt template.sbt --eggnog IWGSC_v1.1_HC_eggnog.out.txt.emapper.annotations --iprscan output.interproscan.out.xml --busco_db embryophyta --cpus 10 -d /data -o ./`
This is my log file
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/3673993/funannotate-annotate.log)

 Custom annotations  file must be offered? How can get this file?

**Comment by nextgenusfs** [comment]
Might be a bug. Upgrade to newest version and run again. If still have a problem I will look into it. Logfile says you should have had ~23,000 gene names and product deflines.

**Comment by shenweima** [comment]
I have tested it using new version of 1.6.0 , but it not worked. It lost all functional information using new version. I guss this is caused by gene id and mRNA id or protein id. My gene id is `TraesCS4B02G000100`, mRNA id `TraesCS4B02G000100.1` and protein id is `TraesCS4B02G000100.1`.

**Comment by nextgenusfs** [comment]
Yes I think this is due to the gene names -- it is expecting funannotate/NCBI names, ie locus tag that has an underscore in it.  I tried to relax this threshold with this: https://github.com/nextgenusfs/funannotate/commit/84219c6cffaefb2d4bd0159cb5d84f8f262c27a4.

1) try this update with `git pull`
2) If still a problem I need to see what the annotate_misc/genome.tbl file looks like as well as what is in the annotate_misc/final.annotations.txt file (I don't need all of it, just need to see what the gene/protein identifiers look like).
