### ISSUE TITLE
Training with SRA reads!

### ISSUE THREAD

**Issue by sunnycqcn** [nextgenusfs/funannotate#346]
Hi Jon,
I used my own sequenced Illumina reads. The pipeline working well. But I downloaded some reads from NCBI, I got the error as following.

[03:52 PM]: OS: linux2, 80 cores, ~ 1057 GB RAM. Python: 2.7.15
[03:52 PM]: Running funannotate v1.6.0-84219c6
[03:52 PM]: Adapter and Quality trimming PE reads with Trimmomatic
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/funannotate/bin/funannotate-train.py", line 821, in <module>
    lib.CheckFASTQandFix(trim_reads[0], trim_reads[1]) #if needed to fix they will be fixed in place
  File "/home/AAFC-AAC/fuf/funannotate/lib/library.py", line 650, in CheckFASTQandFix
    for read1, read2 in izip(file1, file2):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/funannotate/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 917, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.
**My NCBI command is** 
fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files SRR8186819
**The fastq format is** 
@1/1
CCGGTTTCTGCGATTGCTTCTTGGATTGTTCCAACTGTTGTATGACATTTTGGTGTCCTTGCGTTACCTTTGGCCAAATCGCAGAGATTGTAGACCAAGGTTCATCTTCATGTGGTAC
+SRR8186819.1 1 length=118
AAFFAJJJJJJJJJJJJJJJJJFJJJFFJJJJJJJJJJJJJJJJJJJJJJJJFJJJAFJJFFAFJJJJJJJFJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

I think this issue is not pipeline code issue. It should be  the format of reads. But I tried lots of times. I can not figure out it. Based on experience, could you have any idea?
Thanks,
Fuyou

**Comment by nextgenusfs** [comment]
So looks like you downloaded according to Trinity docs [that's good]. But it might be because lines 1 and 3 in the FASTQ format don't match.  Some discussion here: https://github.com/mossmatters/HybPiper/issues/40.  What version of biopython are you using?

**Comment by devonorourke** [comment]
I got the same error, and also downloaded according to the Trinity docs. Lines 1 and 3 definitely don't match for any of my downloads either. As a result, I needed to cleanup the quality header line with a bash one(ish) liner below.

Assume the original `reads_r1.fq.gz` file looked like this:
```
@D00430:197:C8H8TANXX:2:2201:1724:1977_forward/1
ATTAGGAATGGTCATTCTGCTGTTCAGCCGTCTGGTCTAA
+SRX3752331.1 D00430:197:C8H8TANXX:2:2201:1724:1977 length=126
BCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEG
```

I executed the command:
```
zcat reads_r1.fq.gz | sed '/^[+SRX3752331]/s/[^ ]* /+/1' | sed 's/ length=.*$/_forward\/1/' > LUgut_1_tmp.fq
```

Which resolved to:
```
@D00430:197:C8H8TANXX:2:2201:1724:1977_forward/1
ATTAGGAATGGTCATTCTGCTGTTCAGCCGTCTGGTCTAA
D00430:197:C8H8TANXX:2:2201:1724:1977_forward/1
BCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEG
```

In your case, it might be much simpler because you can effectively substitute in a single `sed` (or other) command. 

@nextgenusfs  - would it be possible to sample the fastq file during the startup of a Funannotate run and check if the nucleotide header matches the quality score header, and flag a warning in the log file (if this continues to cause headaches?)?

Thanks

**Comment by sunnycqcn** [comment]
Hi Jon,
This one I get the solved with command as following:
fastq-dump --defline-seq '@$sn[_$rn]/$ri' --split-files ERR2027133
Best,
Fuyou

**Comment by nextgenusfs** [comment]
@devonorourke don't you need the third line to start with `+`?  I'm not entirely sure what the real underlying issue is here, perhaps it has something do with how people upload reads to SRA and in what format they are in?  Wouldn't the better solution just be to reformat in the standard way of:
```
@D00430:197:C8H8TANXX:2:2201:1724:1977_forward/1
ATTAGGAATGGTCATTCTGCTGTTCAGCCGTCTGGTCTAA
+
BCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEG
```
Or does that not work?  Would be easiest to just parse the files and remove the quality header and change to `+` -- this would also save space....

**Comment by devonorourke** [comment]
Whoops - yes indeed @nextgenusfs , I failed to post the appropriate third line to start with the obligatory `+` (though note that my bash command would produce that plus sign... It was just a copy/paste mistake).

I don't know if a single `+` is sufficient, or if the headers must be exact matches for lines 1 and 3. My revision made the lines exact matches, and Funannotate is now at the PASA alignment stage. Definitely worth a test; 100% agree that if you can hack it with a simple `+` for line 3 and nothing else, that'd be very helpful for disk space. Though, it's also possible that once you concatenate all the reads and feed them into Trimmomatic, I suppose there is an opportunity to rename both the line1 and line3 headers to be as sparse as possible.

As it stands now, my issue related to this thread was resolved by making lines 1/3 exact matches. Hopefully things keep on chugging. 

How long do you suppose it take to align 80k transcripts on one thread? 

Thanks!

**Comment by nextgenusfs** [comment]
I have a "FASTQfixer" function in the code, but it was not being triggered by these "errors".  The original error that @sunnycqcn identified is related to the Biopython FASTQ iterator that stumbled when the sequence and quality scores headers were not the same value -- but I know it works to simply just stick with the simple 3rd line "+" -- at least I never have any of my data with any headers on the 3rd line. The issue is more that SRA is kind of annoying and you can't always assume that whomever uploaded the data used the actual raw Illumina data.

You are through the slow part I think (Trinity normalization and assembly) -- so shouldn't take too long, actually the alignments are fast (minimap2 and blat) but importing into SQL is the slow-ish step.  But PASA should run fairly quickly.  The slow part with SQLite/PASA is `funannotate update` which uses PASAs "annotation comparison" mode to extend UTRs and validate transcripts.  Hopefully you get decent results from the pipeline.
