### ISSUE TITLE
GAG failure

### ISSUE THREAD

**Issue by antben** [nextgenusfs/funannotate#37]
Hi Jon,

I'm getting this error:
```
[03:01:06 PM]: Converting to preliminary Genbank format
Traceback (most recent call last):
  File "/data/local/funannotate/2016-08-24/funannotate/bin/funannotate-predict.py", line 956, in <module>
    shutil.copyfile(os.path.join('gag2', 'genome.fasta'), os.path.join('gag2', 'genome.fsa'))
  File "/usr/local/python/2.7.12/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'gag2/genome.fasta'
```
When I try to run the second GAG conversion manually, I get: 
  File "/Genomics/kocherlab/berubin/local/src/GAG/src/gff_reader.py", line 352, in read_file
    parent_gene = self.genes[mrna.parent_id]
KeyError: 'evm.TU.2371.1'

The "mRNA", "CDS", and "exon" features for that parent are present in "cleaned.gff3" but the "gene" feature is not. Notably, that "gene" feature is in "bad_models.gff". So the issue seems to stem from the elimination of bad "gene" features but not all of the corresponding "mRNA", "CDS", and "exons". It looks like there are only 38 features that are missing their parent. Does this make sense? Any suggestions for working around the problem?

Thanks,
Ben

**Comment by nextgenusfs** [comment]
In the bad_models.gff file - does that particular gene say why it was removed (last column 9, something like ;remove_reason=).  It sounds like the gene was ID to be removed, but the script missed the child features for some reason.  Could you paste in the original GFF features for that particular model (i.e. gene, mRNA, CDS, exons) and then the matches in the bad_models.gff file.

**Comment by antben** [comment]
I think that there are eight gene features that get removed but whose children are left behind. They all are removed for unkown reason (e.g. "2371    EVM     gene    135     750     .       -       .       ID=evm.TU.2371.1;Name=EVM%20prediction%202371.1;remove_reason=unknown;").

The original features in evm.trnascan.gff:
2371    EVM     gene    135     750     .       -       .       ID=evm.TU.2371.1;Name=EVM%20prediction%202371.1
2371    EVM     mRNA    135     750     .       -       .       ID=evm.model.2371.1;Parent=evm.TU.2371.1;Name=EVM%20prediction%202371.1
2371    EVM     exon    650     750     .       -       .       ID=evm.model.2371.1.exon1;Parent=evm.model.2371.1
2371    EVM     CDS     650     750     .       -       1       ID=cds.evm.model.2371.1;Parent=evm.model.2371.1
2371    EVM     exon    135     580     .       -       .       ID=evm.model.2371.1.exon2;Parent=evm.model.2371.1
2371    EVM     CDS     135     580     .       -       2       ID=cds.evm.model.2371.1;Parent=evm.model.2371.1

And the match from bad_models.gff:
2371    EVM     gene    135     750     .       -       .       ID=evm.TU.2371.1;Name=EVM%20prediction%202371.1;remove_reason=unknown;

**Comment by nextgenusfs** [comment]
Hi Ben,
So basically here is what the removeBadModels function does (this is very hackish because parsing GFF files properly parent:child features is difficult - but certainly this could be improved):   
1) runs BedTools intersect with the GFF from repeat masker and your GFF and finds gene models that are at least 90% overlapping with repeat region
2) then parses BLASTP search of transposon protein models
3) looks for proteins that are less than specified length or contain XXX (meaning they are spanning regions of ambiguous DNA sequence).  
4) finally, it takes all of these "bad gene models" into a list and then tries to reduce that list to the gene name, i.e. the part of the name that is the same in all parent:child features, in this case it is `2371.1`.  The function then parses the incoming GFF file and uses a regex search (search is setup to catch the basename followed by a semi-colon to make sure it isn't also matching something like `2371.12`) for matching lines in the "bad model list",  dumps the lines that don't match into the "good GFF" and those that match into the "bad GFF".  

It seems like the regex search missed the children of these models or that the gene model got picked up and it was not suppose to. What is strange is that I took your GFF file, recapitulated the regex search on my computer and it gets picked up, so I'm not sure what the problem is.  Here is the little test that I did if you want to try it.  Here's my version of python: `Python 2.7.12: GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)`

[Your GFF snippets file](https://github.com/nextgenusfs/funannotate/files/639867/test.txt)
```
import re
remove = ['evm.TU.2371.1', 'evm.TU.2372.5', 'evm.model.2371.2']
remove = [w.replace('evm.TU.','') for w in remove]
remove = [w.replace('evm.model.','') for w in remove]
remove_match = re.compile(r'\b(?:%s)[\.;]+\b' % '|'.join(remove))
with open('test.txt', 'rU') as input:
     for line in input:
          if not remove_match.search(line):
               print "Good Hits: "+line
          else:
               print "Bad Hits: "+line
```
This then output:
```
Bad Hits: 2371    EVM     gene    135     750     .       -       .       ID=evm.TU.2371.1;Name=EVM%20prediction%202371.1
Bad Hits: 2371    EVM     mRNA    135     750     .       -       .       ID=evm.model.2371.1;Parent=evm.TU.2371.1;Name=EVM%20prediction%202371.1
Bad Hits: 2371    EVM     exon    650     750     .       -       .       ID=evm.model.2371.1.exon1;Parent=evm.model.2371.1
Bad Hits: 2371    EVM     CDS     650     750     .       -       1       ID=cds.evm.model.2371.1;Parent=evm.model.2371.1
Bad Hits: 2371    EVM     exon    135     580     .       -       .       ID=evm.model.2371.1.exon2;Parent=evm.model.2371.1
Bad Hits: 2371    EVM     CDS     135     580     .       -       2       ID=cds.evm.model.2371.1;Parent=evm.model.2371.1
```

**Comment by antben** [comment]
Hey Jon,

Yes, this is a bit mysterious. The one thing that looks a little suspicious
is that the protein translation in "gag1/genome.proteins.fasta" looks quite
bad:

>evm.model.2371.1 protein
SRQSFVHWIL*I*KNII**ILILEQKAMSKNIMTLQLIRRTLLIVL*TLRLIFQIP**NPEIRLAR*KLIVRT*KKRRLSF*NNNLF*ILCMTNRPPAKLYF*ILLGQNFLPHLMMK**KLLDGIFKGTCCL*IFLTKKALTTAALLKTGWIL*LKSY*MTILDFLNRMRIKPPLGHLNMT

I don't actually see how that could be causing the problem though.

I just noticed that model 2023 is in "bad_models.gff". Could that be
matching just the gene feature of 2371? Since the description is
"Name=EVM%20prediction%202371.1" and, therefore, contains the string "2023"?

Is there an easy way that I can feed a corrected version of "cleaned.gff3"
into the pipeline and just have it continue from that step? I'm working on
a cluster so can't modify the code directly, though I am working on
installing locally as well.

Thanks,
Ben

**Comment by nextgenusfs** [comment]
So others have reported problems with the GAG protein translations, thus I'm not throwing out gene models that have internal stops at this point (because I think there is a chance they are wrong - they will be caught later on in the script by tbl2asn). 

I think that you are probably right, that this specific model isn't suppose to be a "bad model" and is getting picked up by another gene model.  Which means I need to have a better regex search, or re-write this whole function with a different approach.  

Unfortunately there isn't a way in the current code to skip those two steps.  

I'm working right now on another module for funannotate compare, so likely have a release ready in next few days.  Would it be possible to send me your entire GFF file (evm.trnascan.gff) and then also the bad_models.gff?  I want to be sure I fix your problem. You can just send to my email if that works, not sure how big it is - but otherwise a dropbox link or something?

**Comment by antben** [comment]
The gff's are attached. Let me know if you need anything else from me.
Thanks for the help!

**Comment by nextgenusfs** [comment]
Hi Ben, Doesn't look like they went through, since this is on GitHub Issues, you may need to just send me a clean email and attach them.  nextgen.usfs at gmail dot com.

**Comment by nextgenusfs** [comment]
Hopefully this is fixed here: https://github.com/nextgenusfs/funannotate/commit/405ab37e2271804b34af21c82eabe26adf391d3b
