### ISSUE TITLE
Annotation BUSCO step fails without first copying input proteins to annotate_misc folder

### ISSUE THREAD

**Issue by hyphaltip** [nextgenusfs/funannotate#38]
When I run with previously generated GFF/annotation the BUSCO step fails:
`funannotate annotate --gff GFF --fasta FASTA --proteins PROTEINS ... -o annotate `
This is because I need to first
`cp PROTEINS annotate/misc_annotation/PROTEINS`
or else BUSCO step fails. 

So I don't see verbose/debug options in there but it might be nice for the subprocess spawning to not redirect stderr/stdout to NULL if --debug and/or --verbose flag is provided to funannotate? To debug this myself I had to edit the code and change this redirection.

**Comment by nextgenusfs** [comment]
Ok - I thought I had just made it default to the absolute PATH of the proteins file, but something must be off.  Yes the logging is not the greatest, I'm slowing trying to improve.

**Comment by nextgenusfs** [comment]
I think this was due to the output folder not being created if you didn't pass a genbank file or funannotate predict folder, this should fix it https://github.com/nextgenusfs/funannotate/commit/4f74ea8bf2f87ec12edbeaa51d89de7174960650

And I'm working now on better logging, I need to swap all the subprocess.call with the lib.runSuprocess function (located in library) which will pipe the STDERR/STDOUT to the log file but not to the terminal.  I think that should at least capture when calls to external programs fail (I hope).  It will make the log file a bit messy, but probably better to have the information than losing it in FNULL.
