### ISSUE TITLE
funannotate compare issues

### ISSUE THREAD

**Issue by aberaslop** [nextgenusfs/funannotate#429]
Hi Jon,

First of all, thank you for this program, it is really awesome! 
I have annotated 19 genomes with funannotate v 1.7.2. with no problem (OS: linux2, 24 cores, ~ 264 GB RAM. Python: 2.7.15). I then proceeded to run funannotate compare and although it seems to have run ok, I have encountered a number of weird issues.

1. The cazyme graph is missing a species. The x axis shows the name, but the barplot is empty. The original cazyme analysis after funannotate annotate for that species shows the results normally. It is not a big problem because I can manually include the data for this species, but I don't know if this is a sign of bigger problems. (Update: this species is also missing from the Pfam, merops and signalp analyses )

2. The COGS.all.summary.csv is missing another species (a completely different one). 

3. Go_enrichment directory is empty. 

4. All BGCs have been classified as "Other". However, when I look in the antiSMASH output, BGCs have been binned into all types of metabolites. 

I suspect all these issues have different origins. Any insights you may have regarding any of them is welcome. Looking in funannotate_compare.log (attached), I have seen some warnings regarding diamond and a couple others. Could this be the root of some of the problems? If I could tackle any of this issues, how could I go about fixing them and resuming funannotate compare from that point on? Or is it just better to start the comparison from the beginning? 

Thank you so much!

Aileen

[funannotate-compare.log](https://github.com/nextgenusfs/funannotate/files/4683987/funannotate-compare.log)
[funannotate_check.log](https://github.com/nextgenusfs/funannotate/files/4684007/funannotate_check.log)

**Comment by nextgenusfs** [comment]
The `compare` scripts hasn't really been updated in quite some time -- we had some plans to update it but generally haven't had time to do it yet.  

From your log file, the missing species is likely this one I'm guessing: 
```
[05/22/20 08:32:25]: working on Escovopsis myrmecocrypta
```
I don't know if this is fixed in most recent release, but the spaces cause some inconsistencies between some of the tools.  I thought I had pushed a fix a while ago to address this, but I don't recall the version.

**Comment by aberaslop** [comment]
Hi Jon,

thank you for your answer.  E myrmecocrypta worked fine, but E dentigerumH and E_weberi had issues. Is it possible to run funannotate compare script by script? Maybe that way I could solve some of the problems. 

Thanks!

A.

**Comment by nextgenusfs** [comment]
You should be able to try to run those "problematic" genomes in `funannotate compare` by themselves to perhaps isolate if there are any problems with the GBK files.

**Comment by aberaslop** [comment]
Thanks, that is a great idea! I will do so.

Also, what are the individual steps that funannotate runs to perform the GO enrichment? How are the GO terms annotated? I'd like to perform a GO enrichment analysis with my genomes as well as others that have been annotated by others, outside funannotate, but I am struggling with adding GO terms. 
Thanks!!
A.

**Comment by nextgenusfs** [comment]
You will want to make sure GO terms are added with the same method for all genomes, otherwise the enrichment experiment won't have much meaning.  Funannotate pulls the GO terms from the InterProScan results. So you could run `funannotate annotate` on all of your genomes (and include InterProScan results for each) and that should add the necessary GO terms.  The enrichment experiment is done with `goatools` -- script is here: https://github.com/nextgenusfs/funannotate/blob/master/funannotate/aux_scripts/enrichment_parallel.py

**Comment by aberaslop** [comment]
Thank you!

**Comment by athulmenon** [comment]
Hi Jon,

I have 7 species which have ran through interproscan using the below command.

`~/interproscan-5.48-83.0/interproscan.sh -i GCF_900079805.1_Fusarium_fujikuroi_IMI58289_V2_protein.faa -b ipr_results -f XML --cpu 10 -dp -goterms –disable-precalc`

Later ran with eggnog, antismash and phobius modules.

Next we ran annotate module on all these species and went to comparison. We have used annotation folders as the input. In the compare results we are not able to find GO enrichments, InterProScan Domains per Genome Results and COGs missing. Below is the log. All this has been ran through docker wrapper script. One of the species were generated using Predict module and later annotated, we can see the GO enrichment for that but not for others.

`[Feb 12 07:13 AM]: OS: Debian GNU/Linux 10, 12 cores, ~ 74 GB RAM. Python: 3.7.9
[Feb 12 07:13 AM]: Running 1.8.4
[Feb 12 07:13 AM]: Now parsing 7 genomes
[Feb 12 07:13 AM]: working on Fusarium equiseti
[Feb 12 07:14 AM]: working on Fusarium graminearum PH-1
[Feb 12 07:15 AM]: working on Fusarium pseudograminearum CS3096
[Feb 12 07:15 AM]: working on Fusarium coffeatum
[Feb 12 07:16 AM]: working on Fusarium oxysporum f. sp. lycopersici 4287
[Feb 12 07:17 AM]: working on Fusarium proliferatum ET1
[Feb 12 07:18 AM]: working on Fusarium subglutinans
[Feb 12 07:19 AM]: Summarizing secondary metabolism gene clusters
[Feb 12 07:19 AM]: Summarizing PFAM domain results
[Feb 12 07:19 AM]: Summarizing InterProScan results
[Feb 12 07:19 AM]: Loading InterPro descriptions
[Feb 12 07:19 AM]: Summarizing MEROPS protease results
[Feb 12 07:19 AM]: found 34/103 MEROPS familes with stdev >= 1.000000
/venv/lib/python3.7/site-packages/funannotate/library.py:7865: MatplotlibDeprecationWarning: Calling add_axes() without argument is deprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
  cbar_ax = fig.add_axes(shrink=0.4)
[Feb 12 07:19 AM]: Summarizing CAZyme results
[Feb 12 07:19 AM]: found 48/152 CAZy familes with stdev >= 1.000000
/venv/lib/python3.7/site-packages/funannotate/library.py:7865: MatplotlibDeprecationWarning: Calling add_axes() without argument is deprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
  cbar_ax = fig.add_axes(shrink=0.4)
[Feb 12 07:19 AM]: No COG annotations found
[Feb 12 07:19 AM]: Summarizing secreted protein results
[Feb 12 07:19 AM]: Summarizing fungal transcription factors
/venv/lib/python3.7/site-packages/funannotate/library.py:7865: MatplotlibDeprecationWarning: Calling add_axes() without argument is deprecated since 3.3 and will be removed two minor releases later. You may want to use add_subplot() instead.
  cbar_ax = fig.add_axes(shrink=0.4)
[Feb 12 07:19 AM]: Running GO enrichment for each genome
  WARNING: skipping Fusarium_coffeatum.txt as no GO terms
  WARNING: skipping Fusarium_graminearum_PH-1.txt as no GO terms
  WARNING: skipping Fusarium_oxysporum_f._sp._lycopersici_4287.txt as no GO terms
  WARNING: skipping Fusarium_proliferatum_ET1.txt as no GO terms
  WARNING: skipping Fusarium_pseudograminearum_CS3096.txt as no GO terms
  WARNING: skipping Fusarium_subglutinans.txt as no GO terms
/venv/lib/python3.7/site-packages/funannotate/compare.py:803: FutureWarning: The default value of regex will change from True to False in a future version.
  df.columns = df.columns.str.replace(r'^# ', '')
[Feb 12 07:22 AM]: Running orthologous clustering tool, ProteinOrtho.  This may take awhile...
[Feb 12 07:52 AM]: Compiling all annotations for each genome
[Feb 12 07:54 AM]: Inferring phylogeny using RAxML
[Feb 12 07:54 AM]: Found 1048 single copy BUSCO orthologs, will randomly select 500 to infer phylogeny
[Feb 12 08:17 AM]: Compressing results to output file: funannotate_compare.tar.gz
[Feb 12 08:23 AM]: Funannotate compare completed successfully!
`

Can you please let me know how to include these annotations?
Thanks,
Athul
