### ISSUE TITLE
Funannotate predict output

### ISSUE THREAD

**Issue by vcastroagudin** [nextgenusfs/funannotate#442]
My discrepancy report file from FUNANNOTATE PREDICT says that "all the proteins have been named as "hypothetical proteins". Is that correct? Does the protein get their "correct name"once funannotate annotate is run?

Thanks.
[Calonectria_pseudonaviculata.discrepency.report.txt](https://github.com/nextgenusfs/funannotate/files/4833753/Calonectria_pseudonaviculata.discrepency.report.txt)

**Comment by hyphaltip** [comment]
did you run `funannotate annotate` step - names and function are assigned through a variety of databases being pulled in.

**Comment by vcastroagudin** [comment]
No yet, I am still in the previous step. I want to make sure that the outut of the prediction step is correct.

It from the f. predict step that i got the "hypothetical protein" name in my discrepancy report file.

**Comment by nextgenusfs** [comment]
Yes that is the expected output -- due to NCBI submission rules, controlled vocabulary, and the potential problems with assigning gene names and product definitions from automated primary sequence only pipelines, more than likely even after you run `funannotate annotate` most of your genes will still be hypothetical proteins. This is by design.  You can search the closed issues for lots of questions about this.
