### ISSUE TITLE
gmap-gsnap make check fail -> funannotate installation crashes on Ubuntu 16.04 in Virtualbox

### ISSUE THREAD

**Issue by MichaelFokinNZ** [nextgenusfs/funannotate#50]
Hi, this seems to be not a unique case. After that the installation terminated... :(
[funannotate fail log.txt](https://github.com/nextgenusfs/funannotate/files/840403/funannotate.fail.log.txt)

Last 15 lines from /home/osboxes/.cache/Homebrew/Logs/gmap-gsnap/03.make:
Makefile:577: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/tmp/gmap-gsnap-20170314-23958-1otx3dd/gmap-2017-01-14/tests'
Makefile:683: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/tmp/gmap-gsnap-20170314-23958-1otx3dd/gmap-2017-01-14/tests'
Makefile:749: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/tmp/gmap-gsnap-20170314-23958-1otx3dd/gmap-2017-01-14/tests'
Makefile:432: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

These open issues may also help:
gmap-gsnap: make check fails on Linuxbrew https://github.com/Homebrew/homebrew-science/pull/5110
Error GMAP-GSNAP install on macOS Sierra using brewed Perl https://github.com/Homebrew/homebrew-science/issues/4584

[gmap-gsnap_log.txt](https://github.com/nextgenusfs/funannotate/files/840320/gmap-gsnap_log.txt)

**Comment by MichaelFokinNZ** [comment]
the same on Ubuntu 16.10 (Yakkety Yak)

**Comment by nextgenusfs** [comment]
The problem I had was a Perl $PATH issue, where I had installed a home-brewed version of Perl and installed required perl modules in that version.  However, during the build the configure script was referencing system perl and thus could not find required modules.  I fixed this by adding the following to the brew formula:
```
depends_on "perl" => :build
```
But it isn't too bad to manually install (http://research-pub.gene.com/gmap/), so can take that route and comment out the gmap-gnsap in the funanntoate formula after you've gotten it installed. 

Sorry this is such a pain, LinuxBrew is not quite perfect yet....probably in part due to the large number of linux distributions out there. On Mac, home-brew seems to work a lot better.

**Comment by MichaelFokinNZ** [comment]
hi, thank you for reply, it is not a big deal to install gmap manually, but
how would you  recommend doing that to show "brew install unannotate" that
gmap has been already installed? Any specific folder?path?

Overall looks strange because ive tried all the most common and updated
ubuntu distr.  I do install perl modules to system perl, but without
sudo(as written in your installation readme) they usually come to
/home/user/perl5. Not my case.
Also the link to repbase is outdated...

Sorry, it my first experience with brew, so it is not clear if i can edit
it... Overall docker or vbox vm looks way more convenient for such a
complex pipeline. but i am just a user :)

**Comment by MichaelFokinNZ** [comment]
Oh, may be the perl modules location is an issue - where do you advise to
install them?

On 15/03/2017 9:20 am, "Mikhail Fokin" <mikhail.fokin@gmail.com> wrote:

hi, thank you for reply, it is not a big deal to install gmap manually, but
how would you  recommend doing that to show "brew install unannotate" that
gmap has been already installed? Any specific folder?path?

Overall looks strange because ive tried all the most common and updated
ubuntu distr.  I do install perl modules to system perl, but without
sudo(as written in your installation readme) they usually come to
/home/user/perl5. Not my case.
Also the link to repbase is outdated...

Sorry, it my first experience with brew, so it is not clear if i can edit
it... Overall docker or vbox vm looks way more convenient for such a
complex pipeline. but i am just a user :)

**Comment by nextgenusfs** [comment]
You can run `brew edit funannotate` to see the formula that installs the packages, its written in Ruby.  You can simply comment out the gmap-gnsap entry. Alternatively you can run:
`brew install --ignore-dependencies funannotate` which will only install funannotate.  funannotate will run checks for the programs that it needs prior to running - if you find that easier to install them one by one.  The script `funannotate setup --all` will download databases that you need as well as check your installation and tell you what is not installed as well.

Alternatively you can just clone the repository and than manually install all the missing parts.  `git clone https://github.com/nextgenusfs/funannotate.git`.

The [ubuntu install tutorial](https://github.com/nextgenusfs/funannotate/blob/master/docs/ubuntu_install.md) were all the commands I needed to install on virtual box running Ubuntu. 

I've tried to make it a easy as I can to install using a package manager, you obviously don't have to use it though.  I have no experience with docker, when I find some time I can look into writing a container, I'm hesitant though as I'm sure it won't be as easy as it seems.  There are lots of databases that need to be downloaded, not sure how that would work with docker containers.  There are also several programs that have to be manually downloaded and setup due to licensing.  If you have suggestions for a better way, I'm all ears.

**Comment by MichaelFokinNZ** [comment]
_depends_on "perl" => :build_ doesn't work for me, will skip gmap. 
Having gmap installed separately/manually, should be any gmap related ENV specified for funannotate?

**Comment by MichaelFokinNZ** [comment]
another issue:
- Repeatmasker config.txt file has linuxbrew user home specified. 
- when running ./configure manually seems that library have to be already in place (checking now)

Missing full RepeatMasker repeat library!
  The version of RepeatMasker you have selected was installed
  with the minimal RepeatMasker repeat library.  This library
  is not sufficient for use with RepeatModeler and
  RepeatClassifier.  Please obtain the full repeat database
  from http://www.girinst.org and rerun RepeatMasker/configure
  and the RepeatModeler/configure scripts.

**Comment by nextgenusfs** [comment]
No you just need gmap installed, any somewhat recent version should be fine.  The genome databases are built on the fly.
