### ISSUE TITLE
weights of multiple protein evidence files

### ISSUE THREAD

**Issue by PlantDr430** [nextgenusfs/funannotate#513]
Hello,

I was wondering if there was a function to alter the weights of multiple protein evidence files.

Similar to how you can alter the weights of different gffs files such as:

` --other_gff prediction1.gff3:5 prediction2.gff3:1`

Could this be similarly done if I wanted to weight different protein evidence files? Such as:

`--protein_evidence high_conf.fasta:5 medium_conf.fasta:2.5 low_conf.fasta:1`

**Comment by nextgenusfs** [comment]
There is currently not a way to do this.  It is possible -- basically you tell EVM that you have a different "source" (the second field of GFF3 format) and give it a desired weight in the weights.txt file.  I've not really tested, but how EVM works I wouldn't expect this to have a very large effect (if any) on the resulting predictions.  That is because EVM only uses the evidences (transcripts/proteins) to pick between de novo gene models at the same locus, it will not predict de novo genes from any of the transcript/protein alignments, they simply weight how it chooses the de novo model.  Generally I wouldn't expect you to have a whole bunch of protein alignments at the same locus that would have different intron/exon boundaries -- if people do have these data please let me know.  Remember that you should likely not use proteins derived from other genome annotations (ie ab initio derived gene models) as evidence -- but rather proteins that have been curated/experimentally derived. This is to make sure you aren't further biasing the de novo prediction algorithms by feeding them previously predicted genes/proteins as it just telling the algorithms they are doing great when said genes/proteins haven't been validated. I find transcript evidence more useful -- so similarly perhaps weighting the transcript evidence could be helpful.
