### ISSUE TITLE
user introduction of funannotate docker 

### ISSUE THREAD

**Issue by ybdong919** [nextgenusfs/funannotate#526]
Hi,
Would you please tell me where I could find a user manual for docker-funannotate. For example, how to run prediction using a docker-funannotate? how to run function annotation using the docker-funannotate?

**Comment by nextgenusfs** [comment]
It is exactly the same as normal funannotate, just substitute `funannotate-docker` for `funannotate` in the manual.  ie you can run:
```
funannotate-docker predict -h
```
Which will spin up the docker image into a container and show you the help menu.

One thing that is perhaps missing would be that `funannotate-docker` needs to be executable on your system as well as be in your PATH in order to call it from anywhere on your file system. To make the bash `funannotate-docker` script executable, after downloading you would run:
```
chmod +x /path/to/wherever/funannotate-docker
```
