### ISSUE TITLE
extracting augustus model

### ISSUE THREAD

**Issue by caonetto** [nextgenusfs/funannotate#592]
Just wondering if its possible to extract the augustus training model after a funannotate run to use it later while running augustus independetly? If it is, where is the model located?

Thanks in advance!

**Comment by nextgenusfs** [comment]
Augustus parameters are stored in a nested folder structure, ie `$AUGUSTUS_CONFIG_PATH/species` is where they need to be to run by Augustus. Due to this directory not being writable by all users on many HPC's, funannotate copies these data to `$FUNANNOTATE_DB/trained_species/"species_name_here"/augustus`, which is what is essentially being populated by the `funannotate species` command. This is also separate from the files used at runtime for the same reason, ie some system admins may not have this shared database location writable.

When you run `funannotate predict` the training files will be located in `outfolder/predict_misc/ab_initio_parameters/augustus`.  So short story would be that you copy the directory from this location to `$AUGUSTUS_CONFIG_PATH/species` and then it would be available to use with `augustus --species=whatever` if you named the folder `whatever`.

**Comment by caonetto** [comment]
Thanks for the quick response. Inside the outfolder/predict_misc/ab_initio_parameters/augustus folder there is a species folder and inside there is another folder with my species name. I assume this is the right folder with the final training parameters used by funannotate? not the intermediate BUSCO species folderl.

Thanks again.

**Comment by nextgenusfs** [comment]
Yep I think that sounds right, compare the contents of that folder with any of the species listed in the pre-installed augustus location.

**Comment by caonetto** [comment]
Yes, the training files are the same. but the BUSCO folder also contains a training parameter set, but I am assuming this is what is used to create the final training model thats located in the folder with my species name.

**Comment by nextgenusfs** [comment]
So if you ran this:
```
$ funannotate predict -i test.softmasked.fa --protein_evidence protein.evidence.fasta -o annotate \
     --cpus 7 --species "Awesome testicus"
```
Then you could run something like:
```
cp -R annotate/predict_misc/ab_initio_parameters/augustus/species/awesome_testicus $AUGUSTUS_CONFIG_PATH/species/awesome_testicus
```
