### ISSUE TITLE
checking progress of funannotate-runEVM.py

### ISSUE THREAD

**Issue by LRFreeborn** [nextgenusfs/funannotate#595]
Hello,

I'm using v1.8.3 installed with conda. `funannoate check` suggests all the dependencies are installed.

I've run the following command:
`funannotate predict -i my_sorted_genome.fa -o fun_predict --species fly --cpus 16`

As far as I can tell, everything progressed smoothly until `funannotate-runEVM.py`. The script appears stuck, as my funannotate-EVM.log hasn't printed anything after the following: 

> Finished partitioning, generating command list

My `fun_predict/predict_misc/EVM`directory populated with scaffold directories, generated the `evm.out` and `evm.out.log`  files in each directory, but then nothing new is created or prints to log files (for hours and hours).

Does it make sense that `funannotate-runEVM.py` takes a long time to complete the 'generating command list' step? Is there a way to check if it's hung or not? 

I'm attaching my log file.

Thank you!
[funannotate-predict.log.txt](https://github.com/nextgenusfs/funannotate/files/6462652/funannotate-predict.log.txt)

**Comment by nextgenusfs** [comment]
There should be an EVM log file as well in the log files directory, any hints in there? This is a fairly large genome, its possible its stuck somewhere in partitioning. 

But there are a few other problems with your command, you should read this: https://funannotate.readthedocs.io/en/latest/tutorials.html#non-fungal-genomes-higher-eukaryotes.  

Likely you want to add these flags to your command, and actually delete this output and try again as based on the gene numbers from the different tools it doesn't look like very consistent results:
```
--organism other --busco_db insecta --max_intronlen 20000 --repeats2evm
```
It also looks to me like perhaps `snap` is not compiled properly due to the very few number of genes.

**Comment by LRFreeborn** [comment]
I ran predict again as follows:
`funannotate predict -i my_sorted_genoma.fa -o fun_pred_2 --species aedes --cpus 16 --organism other --busco_db insecta --max_intronlen 20000 --repeats2evm`

The _exact_ same thing happened again, where it stopped doing anything at `funannotate-runEVM.py`. It wasn't using any CPUs or memory at that point. The funannotate-EVM.log file (attached) doesn't give me any hints.

I'm working on the snap issue (using #386 as a reference), but do you have any other ideas why it might be getting stuck at that point? Do you have any suggestions for troubleshooting this issue?

Thank you!

[funannotate-EVM.log](https://github.com/nextgenusfs/funannotate/files/6516761/funannotate-EVM.log)

**Comment by LRFreeborn** [comment]
An update to the thread to say that, as you may suspect, funannotate predict worked with `--weights snap:0`.
