### ISSUE TITLE
Is it possible to use RepeatMasker as a conda environment?

### ISSUE THREAD

**Issue by hutchinsonmiri** [nextgenusfs/funannotate#606]
Hi there, thanks for this great package!

I am wondering if it's possible to use the conda version of RepeatMasker for masking, rather than a hard installed version. I use a community HPC so I don't have write privileges for the home directory so I was hoping I could maybe point Funannotate to the RepeatMasker conda environment instead. Thank you in advance!!!

Miriam

**Comment by nextgenusfs** [comment]
Yes, funannotate just wants the soft-masked assembly. So will work better to do this in another environment as there are likely dependency issues getting it all in one. Honestly I've not used repeatmasker/modeler since repbase license has changed so I don't think newest versions work with the funannotate mask wrapper anyway.

**Comment by hutchinsonmiri** [comment]
Gotcha! That makes sense. I will try that.
