### ISSUE TITLE
funannotate annotate tbl2asn error

### ISSUE THREAD

**Issue by thibaultcaron864** [nextgenusfs/funannotate#670]
Hello,
I am using the conda version v1.8.9, with a gff3 from a TSEBRA merge of two braker runs with RNA and proteins, and a softmasked genome. I am only running funannotate util gff2prot, then funannotate iprscan, then funannotate annotate.

This last seems to crash without obvious error at the tbl2asn stage (v25.8; see funannotate log and err attached).

My command: 
nohup funannotate annotate --gff ./LCP06136_corrected.gff3 --fasta ./LCP06136.fa --species "Penicillium roqueforti" --iprscan ./LCP06136_iprscan.xml --database /home/jp/test_funannotate/funannotate_db --busco_db eurotiomycetes --cpus 10 --out ./ > funannotate_annotate.logerr 2>&1 &

Here are the only clue I have in the log-error file: (I cut the long and useless DNA sequences)

[Nov 23 07:06 PM]: Converting to final Genbank format, good luck!
-------------------------------------------------------
('ERROR', 'g3057', {'name': None, 'type': 'mRNA', 'transcript': ['ATG<...long and useless DNA sequence...>TGA', ''], 'cds_transcript': ['ATG<...another long and useless DNA sequence...>TGA', ''], 'protein': ['MEM<...useless AA sequence...>EHS*'], '5UTR': [[], []], '3UTR': [[], []], 'codon_start': [1, 1], 'ids': ['g3057.t1', 'g3057.t2'], 'CDS': [[(121371, 122480), (121377, 122480)], []], 'mRNA': [[(121371, 122480)], []], 'strand': '+', 'gene_synonym': [], 'location': (121371, 122480), 'contig': 's_2', 'product': ['hypothetical protein', 'hypothetical protein', 'hypothetical protein'], 'source': 'funannotate', 'phase': [], 'db_xref': [[], []], 'go_terms': [[], []], 'EC_number': [[], []], 'note': [['BUSCO:EOG091P129I', 'EggNog:ENOG503P4DQ', 'BUSCO:EOG091P129I', 'EggNog:ENOG503P4DQ'], []], 'partialStart': [False, False], 'partialStop': [False, False], 'pseudo': False})

About this "g3057", I first thought that it was because of missing exon corresponding to CDS in the gff3 (3 other cases in the gff3, from TSEBRA merging) but I still get this error after adding them in my "_corrected.gff3".

When I try to run tbl2asn independantly, I got the same discrepancy report (see attached), no log or err, and I do not know if it works well or not... and if it worked, if I can just finish the funannotate annotate command by using this output (supposed to be annotation_misc/tbl2asn/genome.gbf right ?) ?

My command:
/home/thibault/miniconda2/envs/funannotate/bin/python /home/thibault/miniconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/aux_scripts/tbl2asn_parallel.py -i ./annotate_misc/tbl2asn/genome.tbl -f ./annotate_misc/tbl2asn/genome.fsa -o ./annotate_misc/tbl2asn --sbt /home/thibault/miniconda2/envs/funannotate/lib/python3.8/site-packages/funannotate/config/test.sbt -d discrepency.report.txt -s "Penicillium roqueforti" -t "-l paired-ends" -v 1 -c 10 > tbl2asn.log 2> tbl2asn.err &

Please see attached: output from funannotate check, funannotate annotate log and err, discrepency report of tbl2asn, the genome.tbl, and initial gff3.
[funannotate-check.output.txt](https://github.com/nextgenusfs/funannotate/files/7594379/funannotate-check.output.txt)
[funannotate-annotate.log](https://github.com/nextgenusfs/funannotate/files/7594393/funannotate-annotate.log)
[funannotate-annotate.err.txt](https://github.com/nextgenusfs/funannotate/files/7594401/funannotate-annotate.err.txt)
[discrepency.report.txt](https://github.com/nextgenusfs/funannotate/files/7594459/discrepency.report.txt)
[genome.tbl.txt](https://github.com/nextgenusfs/funannotate/files/7594466/genome.tbl.txt)
[LCP06136_corrected.gff3.txt](https://github.com/nextgenusfs/funannotate/files/7596274/LCP06136_corrected.gff3.txt)

Thank you very much in advance for your help, I have been struggling with this for three whole days now, I hope it is not because of a dummy error from myself ! Please let me know if you need more details to solve this.

**Comment by nextgenusfs** [comment]
Hi @thibaultcaron864, sorry you got this error.  If you can also share the genome FASTA file I can try to reproduce locally.  I don't see anything obvious from these log files as to why it would fail unfortunately.  I'm trying to figure out why the 'g3057' model is printed out to stderr as well, I don't see anything obviously wrong with it either.

Per the discrepancy report -- there are a few "FATAL" errors in the log file, but typically that doesn't kill `tbl2asn` it would just fail if you tried to submit to NCBI. My suggestions will depend a little bit on what you are going to do with this genome, eg is the intention to submit to NCBI/Genbank? If so than you would need to rename gene models as that is one of the FATAL errors -- you can do that with `funannotate annotate` using the `--rename` option.  Generally if plan is to submit, I actually submit the genome FASTA file first so that NCBI can assign a locus_tag -- and that locus_tag is what you would want to rename the gene models with.

If you are just interested in the annotation (and not going to submit to NCBI), then effectively the annotation is completed at this stage in the tbl format. This utility script runs the same method, it might be easier to debug I guess:
```
$ funannotate util tbl2gbk

Usage:       funannotate util tbl2gbk <arguments>
version:     1.8.10

Description: Convert NCBI TBL annotations + Genome FASTA to GenBank format.

Required:    -i, --tbl          Annotation in NCBI tbl format
             -f, --fasta        Genome FASTA file.
             -s, --species      Species name, use quotes for binomial, e.g. "Aspergillus fumigatus"
Optional:
             --isolate          Isolate name
             --strain           Strain name
             --sbt              NCBI Submission Template file
             -t, --tbl2asn      Assembly parameters for tbl2asn. Example: "-l paired-ends"
             -o, --output       Output basename
```

I see that I don't have a `tbl2gff3` utility script -- in practice this is never something anybody needs because `tbl` format is really just used for submission to NCBI, however, I can expose this functionality if it is helpful.

**Comment by thibaultcaron864** [comment]
Hello @nextgenusfs,

Thank you very much for your quick reply !

In the meantime I realized that after correcting the gff3 (adding the 4 missing exons, including one in the "g3057" gene) I had run the annotate function with the old version of the iprscan (done with the gff3 with the 4 missing exons). After redoing the iprscan with the "_corrected.gff3", the annotate function worked fine. So finally it was just a dummy error from myself.... My apologies for that...

I did not think yet about the NCBI/Genebank but indeed I might do that, thank you for the tip!

Thanks again for your help!
TC
