### ISSUE TITLE
Not a valid file

### ISSUE THREAD

**Issue by Skhanal2** [nextgenusfs/funannotate#749]
I am having the issue while running funannotate.
After our cluster finally updated the image in singularity. It looks like it all the dependencies are completely installed.

code:
singularity exec /sw/hprc/sw/bio/containers/funannotate-1.8.11-07122022.sif funannotate predict -i TX_1.assembly.fa -o fun_tx_1 --species "Tilletia horrida" --busco_seed_species ustilago
-------------------------------------------------------
[Jul 14 03:06 PM]: OS: Debian GNU/Linux 10, 28 cores, ~ 131 GB RAM. Python: 3.8.13
[Jul 14 03:06 PM]: Running funannotate v1.8.11
[Jul 14 03:06 PM]: Skipping CodingQuarry as no --rna_bam passed
[Jul 14 03:06 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program      Training-Method
  augustus     busco          
  genemark     selftraining   
  glimmerhmm   busco          
  snap         busco          
[Jul 14 03:06 PM]: TX_1.assembly.fa is not a valid file, exiting

this is the first 4 lines of the assembly. 
>scaffold_1
CTCCTCATCACCACTGTCCTCGCCGTTGGCTGCGCAAAGCGGCGGGGCTA
CGCGCTTCTACTGCGGCTGCTTTGGCTGAcgcttgtacggccgcttgtac
actcgcTCTCGCAAGAAGAGGAGCAGCTTCTCGGGCGTGACCGTGTCTCT

I am not sure if this is funannotate issue or installing issue in the cluster.

If anyone has any idea. Any help would be appreciated.

Thank you
Sabin

**Comment by hyphaltip** [comment]
I am not sure if this is an issue in how you run the singularity - you might need to give the full path to the file. it depends on how you have singularity configured to access files in your filesystem since this is data that is outside of the image itsself - this error is from this line which is triggered when python cannot open the file. 

https://github.com/nextgenusfs/funannotate/blob/d96c7e3a84c7704dfef6b1caf29fe55c53d8f6de/funannotate/library.py#L818

I think you need to mount specific folders to be accessible to the singular running image with the -B /--bind option to singularity eg
* https://carpentries-incubator.github.io/singularity-introduction/04-singularity-files/index.html
* https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html
* https://sites.google.com/a/case.edu/hpcc/hpc-cluster/software/Software-Guide/s-t/singularity
* https://singularity-tutorial.github.io/05-bind-mounts/

**Comment by Skhanal2** [comment]
Thank you for reply. I think this issue looks more like singularity issue. I found another way to run it. Thank you

**Comment by Xueliang24** [comment]
> Thank you for reply. I think this issue looks more like singularity issue. I found another way to run it. Thank you

Could you told me how you run it in another way. I also met this problem.

**Comment by Skhanal2** [comment]
yeah. So i was running in University HPRC cluster. I first ran the "srun" in interactive mode after which i could run the above mentioned "singularity exec". 
Later i also figured out that, i can submit the normal job with the code without loading any modules in the HPRC cluster.
Hope this helps

**Comment by Xueliang24** [comment]
> yeah. So i was running in University HPRC cluster. I first ran the "srun" in interactive mode after which i could run the above mentioned "singularity exec". Later i also figured out that, i can submit the normal job with the code without loading any modules in the HPRC cluster. Hope this helps

Thanks
