### ISSUE TITLE
Feature Request: an option to funannotate annotate to provide pre-generated BUSCOs

### ISSUE THREAD

**Issue by docmanny** [nextgenusfs/funannotate#875]
Currently, `funannotate annotate` checks to see if an "annotations.busco.txt" file exists before running the custom built-in version of BUSCO. However, newer versions of BUSCO using ODBv10 now have significantly expanded collections of ortholog groups that can be used for annotation. While it is possible to shoe-horn these annotations into `funannotate annotate` by just manually making this "annotations.busco.txt" file, it would be helpful if the user could provide pre-made BUSCO results to replace the 'run_busco' folder and provide a path to `busco/full_table.tsv` to the program with a `--busco_output` option, similar to how you can provide the output file for eggNOG. 

Happy to make a PR for this if it would help!

**Comment by nextgenusfs** [comment]
You can just download the BUSCO v10 models to your FUNANNOTATE_DB folder and use them directly. Keep the _ovb10 in the name but then for --busco_db just give the base name, ie ascomycota will use models in ascomycota_obv10 folder.

**Comment by docmanny** [comment]
Thank you! I'll try that out.

**Comment by JWDebler** [comment]
I have downloaded the [ascomycota_odb10](https://busco-data.ezlab.org/v5/data/lineages/ascomycota_odb10.2020-09-10.tar.gz)/) dataset and extracted it into the database folder. However, running 

`funannotate annotate -i funannotate_output --cpus 10 --antismash antismash/Ascochyta_rabiei/Ascochyta_rabiei.gbk --iprscan funannotate_output/annotate_misc/iprscan.xml --busco_db ascomycota`

results in 

 `ERROR: ascomycota busco database is not found, install with funannotate setup -b ascomycota`

Turns out I had to include the `_odb10` in the `--busco_db` flag for it to work.

`funannotate annotate -i funannotate_output --cpus 10 --antismash antismash/Ascochyta_rabiei/Ascochyta_rabiei.gbk --iprscan funannotate_output/annotate_misc/iprscan.xml --busco_db ascomycota_odb10`

**Comment by hyphaltip** [comment]
yes you need to give the full version go the OrthoDB clustered version -- since there was previously _odb9 as a version and will I assume eventually be _odb11
